apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: book-catalog
        image: /book
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        env:
        - name: PORT
          value: "5001"
        - name: DATABASE_URL
          value: postgresql://project_part5_0f1z_user:aSGdttT4qyFFitLFDBiCoYjf4X7mpOhk@dpg-crtoqve8ii6s73agpc7g-a.oregon-postgres.render.com/project_part5_0f1z
---

apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - port: 4003
      targetPort: 5001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management
        image: /inventory
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5002
        env:
        - name: PORT
          value: "5002"
        - name: DATABASE_URL
          value: postgresql://project_part5_0f1z_user:aSGdttT4qyFFitLFDBiCoYjf4X7mpOhk@dpg-crtoqve8ii6s73agpc7g-a.oregon-postgres.render.com/project_part5_0f1z
---

apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - port: 4004
      targetPort: 5002